# Generated by Django 4.0.1 on 2022-01-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolregister.semester')),
                ('students', models.ManyToManyField(to='schoolregister.Student')),
                ('subjects', models.ManyToManyField(to='schoolregister.Subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schoolregister.teacher')),
            ],
        ),
    ]
