# Generated by Django 4.0.1 on 2022-01-25 12:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0003_alter_semester_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)])),
                ('end_year', models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)])),
            ],
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'school classes'},
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolregister.teacher'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school_year',
            field=models.ForeignKey(default=1999, on_delete=django.db.models.deletion.RESTRICT, to='schoolregister.schoolyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='school_year',
            field=models.ForeignKey(default='1999', on_delete=django.db.models.deletion.CASCADE, to='schoolregister.schoolyear'),
            preserve_default=False,
        ),
    ]
