# Generated by Django 4.0.1 on 2022-01-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0004_schoolyear_alter_schoolclass_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyear',
            name='end_year',
        ),
    ]
