# Generated by Django 4.0.1 on 2022-01-27 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0006_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.CharField(choices=[('Sprawdzian', 'Sprawdzian'), ('Kartkówka', 'Kartkowka'), ('Odpowiedź', 'Odpowiedz'), ('Praca domowa', 'Praca Domowa'), ('Projekt', 'Projekt'), ('Inne', 'Inne')], default='Inne', max_length=30),
            preserve_default=False,
        ),
    ]
