# Generated by Django 4.0.1 on 2022-04-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0009_rename_grade_grade_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_final_grade',
            field=models.BooleanField(default=False),
        ),
    ]
